init
Puena/password-keeper pull request #1
Opened 2023-05-25 06:05 UTC by Puena

2023-05-26 09:06 UTC, Bazys requested changes

2023-05-26 09:06 UTC, Bazys commented on client/internal/pool/pool.go
> +	ctx     context.Context
только за один контекст в структуре, надо по рукам бить.

2023-05-27 15:58 UTC, Puena commented on client/internal/pool/pool.go
> +	ctx     context.Context
В cobre тоже в структуре -) https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/command.go#L256
возможно они так сделали чтобы не ломать совместимость может быть.
В любом случае я так подумал pool тут не к чему, я переделал на реализацию с семафором.

2023-05-30 20:28 UTC, Bazys approved these changes

2023-05-30 20:28 UTC, Bazys commented on client/internal/repository/base.go
> +func newBaseRepository(db *sqlx.DB, logger *zap.Logger, config *config.Config) *baseRepository {
зачем эта функция? не нашел где она используется.

2023-05-30 20:28 UTC, Bazys commented on server/config/config.go
> +	return nil
а смысл?

2023-05-30 20:28 UTC, Bazys commented on client/internal/adapter/repositories.go
> +func (a *UsecasesRepositoriesAdapter) Viper() usecase.ViperRepository {
очень странный набор функций. Какой в них смысл?

2023-05-30 23:02 UTC, Puena commented on client/internal/repository/base.go
> +func newBaseRepository(db *sqlx.DB, logger *zap.Logger, config *config.Config) *baseRepository {
Комментарий в коде
```go
type storageRepository struct {
	*baseRepository
}

func NewStorageRepository(db *sqlx.DB, config *config.Config, logger *zap.Logger) *storageRepository {
	return &storageRepository{
		&baseRepository{ // предполагалось что я буду использовать её здесь, поэтому создал. 
// Но потом что-то пошло не так и я её негде не использовал... весь неиспользуемый код должен быть удален ?
			logger: logger,
			config: config,
			db:     db,
		},
	}
}

```

2023-05-30 23:02 UTC, Puena commented on server/config/config.go
> +	return nil
Если вопрос про то зачем возвращать ошибку которой никогда не может быть, то это просто задел на будущее, вдруг когда-то надо будет вернуть и чтобы не менять потом обработку вне пакета сделал возврат, вот такой зашквар :( каюсь

2023-05-30 23:02 UTC, Puena commented on client/internal/adapter/repositories.go
> +func (a *UsecasesRepositoriesAdapter) Viper() usecase.ViperRepository {
Честно говоря я не придумал ничего лучше. Поэтому буду рад услышать как надо делать в таких случаях.
Данная конструкция призвана решить две проблемы:
1. Передачу всех репозиториев как одного целого, что также позволяет их все вместе проинициализировать.
2. Избавиться от возможных циклических зависимостей так как мы делаем это все в независомом пакете.

Например если мы хотим использовать репозитории как один входной параметр в usecase, то мы создаем интерфейс:
```go
type Repositorer interface {
	Users() UsersRepository
	Token() TokenRepository
	Chests() ChestRepository
	History() HistoryRepository
}
// при инциализации выглядит так
ucase := usecase.New(repository, cfg, lg)
```
но имея такой интерфейс мы не можем просто записать туда структуру ниже
```go
type Repositories struct {
	Token   *tokenRepository
	Users   *usersRepository
	Chests  *chestsRepository
	History *historyRepository
}
```
// присвоение ниже не работает
```go
var some Repositorer = Repositories{...}  
```
// т.е я не могу без адаптера передать Repositories(структуру) в аргумент которые требует реализации интерфейса Repositorier(интерфейс) тоесть мне необходимо создать getter который должен вернуть интерфейс, если создвать в пакете repository, то придется импортировать usecase в repository, если в gettere возвращать не интерфейс а уже его реализацию *tokenRepostiroy, то компилятор сообщает что *tokenRepository != TokenRepository (интерфейс),
хотя если объявить просто переменную 
```go
 var token TokenRepository = &tokenRepository
```
, то все замечательно работает.
Исходя из этого и чтобы не импортировать интерфейс для  реализации из пакета usecase в пакет repository как зависимость, решено было сделать дополнительный адаптер, короторый будет реализовать этот интерфейс со странными функциями :)) для пакета repository.
и при инициализации usecase мы передаем 
```go
func New(
	repo Repositories, // <-
	config *config.Config,
	logger *zap.Logger) *keeperUseCases {
	return &keeperUseCases{
		usersRepository:   repo.Users(),
		tokenRepository:   repo.Token(),
		chestsRepository:  repo.Chests(),
		historyRepository: repo.History(),
		config:            config,
		logger:            logger,
	}
}
// при инциализации выглядит так
ucase := usecase.New(repository, cfg, lg)
```
если общий интерфейс не делать то пришлось бы прописывать каждый репозиторий отдельно как входной параметр
```go
func New(
	userRepo UserRepository, // <-
        tokenRepo TokenRepository, // <-
        chestsRepo ChestRepository, // <-
        historyRepo HistoryRepository, // <-
	config *config.Config,
	logger *zap.Logger) *keeperUseCases {
	return &keeperUseCases{
		usersRepository:   userRepo,
		tokenRepository:   tokenRepo,
		chestsRepository:  chestsRepo,
		historyRepository: historyRepo,
		config:            config,
		logger:            logger,
	}
}
// соответсвенно при инциализации выглядело бы так
ucase := usecase.New(repository.User, repository.Token, repository,Chests, repository.History, cfg, lg)
```
конечно вместо общего интерфейса можно использовать структуру в пакете usecase
```go
type Repository struct {
	User UserRepository, 
        Token TokenRepository, 
        Chest ChestRepository, 
        History HistoryRepository, 
}
// соответсвенно получили бы
ucase := usecase.New(Repositories{
     User: repository.User,
     Token: repository.Token,
     Chests: repository.CHests,
     History: repository.History,
}, cfg, lg)
```
но при таком раскладе я пару раз забывал передать кокой то из репозиториев и получал панику nil pointer exception в рантайме когда было обращение к пропущенному при инициализации репозиторию.

2023-06-02 11:13 UTC, merged